plugins:
  chb_reward_plugin_enabled:
    default: true
    client: true
  chb_backend_api_url:
    default: "http://localhost:9090"
    client: false
  chb_backend_api_key:
    default: ""
    client: false
  chb_reward_cooldown_seconds:
    default: 60
    client: false
